### PR TITLE
Add retention time to the output of Export to MSP files

### PR DESCRIPTION
**Pull request by asmirn1**
Hi Tomas,

For our data analysis, we needed to output the retention time of a compound into MSP file.  Would you mind make this changes in the official MZmine 2?

Alex.

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Sounds good.

**Comment by asmirn1** [comment]
Thank you!

**Comment by robinschmid** [comment]
Hey Alex,

may I ask how you are using this file output downstream?
Is this the official file structure of the MSP NIST format for library entries?

Cheers
Robin

**Comment by asmirn1** [comment]
Hi Robin,

We export spectra into msp-file, then perform identification using NIST MS Search, and save them to our database.

The only official MSP format specification that I found, is on page 51 of [NIST Standard Reference Database](https://www.nist.gov/sites/default/files/documents/srd/NIST1aVer22Man.pdf). As I understand, they allow optional fields.

I've tested our msp files with "RT:" field in NIST MS Search and MSPepSearch and they were able to read these files without a problem. I haven't tested any other software with our msp files though.

Alex.

**Comment by robinschmid** [comment]
Thanks Alex.
Just asking, because I am developing a new window for submission of DB entries to the GNPS DB. This module also allows the creation of your own databases.

**Pull request merged**
