### PR TITLE
Footer Parameters for SetupDialog

### PR DESCRIPTION
**Pull request by abisarvepalli**
# Updated for GNPSExport
# Updated for SiriusExport

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
The GNPS paper link is pointing to a wrong URL:
https://www.nature.com/nbt/journal/v34/n8/full/nbt.3597.htm

**Comment by tomas-pluskal** [comment]
Also, I wonder if you're planning to add the help files?

**Comment by lfnothias** [comment]
Thanks for seing that ! The l of html is missing

**Comment by lfnothias** [comment]
We would rather keep the link to the documentation on the CCMS webpage in
the footer for now, since it will be the main gateway to GNPS and many
small update will be needed in the coming weeks.
However, we can duplicate the Footer in the Help documentation if you think
this is appropriate.

Regarding Sirius, I will ask Kai if they can coordinate the Help document.
But it will take some time.

LF

**Comment by tomas-pluskal** [comment]
It would be great if you could add a help file for both modules, with a short (1 paragraph) explanation of what the module does and what the parameters mean. Just copy/paste a template from other modules.

**Comment by lfnothias** [comment]
Alright. We are on it.

**Pull request merged**
