### PR TITLE
More options for spectral library match

### PR DESCRIPTION
**Pull request by robinschmid**
More options for spectral library matching

- Remove unmatched signals from composite score (important in MS1 match)
- Changed message to "I am working on it" 
- Option to check all MS2 scans of a FeatureListRow (displays the one with the highest score when compared to a library entry) 
  - before it only took the "best" with the highest TIC
- Option to check for an isotope pattern (interesting for MS1 or for MS2 with full isotope pattern)

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Seem like there is a merge conflict in SpectraIdentificationResultsWindow.java

**Comment by robinschmid** [comment]
working on it.
Already merged this two versions. 

And I have added some button icons and they are now removed from the exported graphs
image

**Comment by robinschmid** [comment]
From my side it is all good to be merged.

**Comment by tomas-pluskal** [comment]
Looks great to me, thanks Robin!

**Pull request merged**
