### PR TITLE
Charge polarity recalculation

### PR DESCRIPTION
**Pull request by abisarvepalli**
- Updated calculation for determining charge and polarity in GNPSExportTask.java
- Updated calculation for determining charge and polarity in SiriusExportTask.java

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Looks good, thanks!

**Comment by tomas-pluskal** [comment]
It seems this PR changes the permissions on the files from 644 to 755. Could you change the permissions back to 644?

**Comment by abisarvepalli** [comment]
Just updated the file permissions!

**Comment by tomas-pluskal** [comment]
Thanks!

**Pull request merged**
