### PR TITLE
Update the version of ADAP. The new jar file includes all dependencies.

### PR DESCRIPTION
**Pull request by asmirn1**
Fix for issue #762

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Hi Alex,
I am not super happy with this solution. Your ADAP jar has now become an "uber-jar" that contains many libraries that are already included with MZmine as standard dependencies (SLF4J, Apache Commons, Guava, etc.). This can create problems because classes on the classpath may be duplicated with different versions that may not work well together and create rare and hard-to-track exceptions.

The dependencies should instead be declared in your pom.xml so Gradle can create a dependency graph.

**Comment by tomas-pluskal** [comment]
Also, we moved the main development to the https://github.com/mzmine/mzmine3/ repository. I may still make one or two bug-fix releases of MZmine 2 from this repository, but the main effort is now focusing on MZmine 3.

**Comment by robinschmid** [comment]
Is the ADAP library on github?
Maybe it is possible to use https://jitpack.io/ to include the ADAP libraries into MZmine. What do you think?

**Comment by asmirn1** [comment]
Hi Tomas, it seems that after switching from Maven to Gradle, gradle couldn't pick up the dependencies that ADAP requires and that would cause the issue #762. That's why I wanted to pack everything into our jar file.

I can pack only specific packages into our jar file instead.

**Comment by asmirn1** [comment]
@robinschmid ADAP is currently on Bitbucket. I'm not familiar with JitPack, let me take a look.

**Comment by tomas-pluskal** [comment]
I think gradle should pick up all the transitive dependencies, but maybe it doesn't pick up the repository definitions. So if you are loading dependencies from some other repositories, you may need to list them in the build.gradle.

**Comment by asmirn1** [comment]
Okay, I'll try the master version again and see why Gradle doesn't pick up ADAP dependencies.

Also, ADAP library is still on Java 8, so it doesn't use java modules, etc. Maybe, that's the reason.

**Comment by tomas-pluskal** [comment]
MZmine also doesn't use java modules, so that is fine.

**Comment by tomas-pluskal** [comment]
Try running `./gradlew -q dependencies`

**Comment by tomas-pluskal** [comment]
I found what the problem is - it's this declaration in the build.gradle:
````
        metadataSources {
            artifact()
        }
````
I added it a while ago because the builds were failing, but now it seems to build fine without this declaration. So I will fix it.

**Comment by tomas-pluskal** [comment]
How badly is ADAP broken in MZmine 2.52? Should I make a new release with the correct dependencies?

**Comment by asmirn1** [comment]
So far, the only module that would give an error is Spectral Deconvolution/Hierarchical Clustering. I'll check other modules.

**Comment by asmirn1** [comment]
Tomas,

Spectral Deconvolution/Multivariate Curve Resolution doesn't work either. It cannot find jsparsehc, which is in the maven central repository: https://mvnrepository.com/artifact/org.du-lab.jsparsehc/jsparsehc. 

FYI, when I try to compile mzmine without 
```
metadataSources {
            artifact()
        }
```
I get an error: 
[error.txt](https://github.com/mzmine/mzmine2/files/3913263/error.txt)

**Comment by tomas-pluskal** [comment]
Please pull the latest master, I added the missing .pom files. It should build fine now. Perhaps we should release the version 2.53 including the fix then?

**Comment by asmirn1** [comment]
@tomas-pluskal I've tested the latest master branch and it works great, no errors for any ADAP modules. Yes, making a new release would be great!

**Pull request closed without merging**
