### PR TITLE
Added EMF and EPS save as options to TIC and XIC graphs

### PR DESCRIPTION
**Pull request by dyrlund**

### CODE REVIEW

**Comment by dyrlund** [comment]
I set the target size of the export to depend on the component size on the screen to follow the implementation of the PNG export. Anyway, since the two new image formats are vector files, then the user can scale the images without loosing quality and I therefore think that we should keep the export simple without user defined width and height parameters.

I will change the implementation to account for the other issues you raised.

**Comment by dyrlund** [comment]
With regards to the error message box for the user, will the following be enough or are you thinking of a message box with the error?
LOG.log(Level.WARNING, "Unable to save image.", e);

**Comment by tomas-pluskal** [comment]
I thought about a message box using MZmineCore.getDesktop().displayErrorMessage(), because this is a purely GUI-based operation.

**Comment by dyrlund** [comment]
Is there a nicer way to code this part of the code?

	       if (file.length() > 3) {
		   if (!file.substring(file.length() - 3).toLowerCase().equals("emf")) {
		       file = file + ".emf";
    		   }
	       }
	       else { file = file + ".emf"; }

**Comment by tomas-pluskal** [comment]
how about
if (file.toLowerCase().endsWith(".emf")) file += ".emf";

**Comment by dyrlund** [comment]
Yep - exactly what I was looking for. Very nice way to solve it :+1:

**Comment by dyrlund** [comment]
I moved the saving of the images to a new class to run it in a separate thread.

**Comment by tomas-pluskal** [comment]
I think the SaveImage class was not included in the commit..

**Comment by dyrlund** [comment]
Wierd. I have added it now.

**Comment by tomas-pluskal** [comment]
Looks good, merging now.

**Pull request merged**
