### PR TITLE
Removed error from msp parser

### PR DESCRIPTION
**Pull request by Annexhc**
Hi Tomas,
I found a bug in the msp DB parser. The parser was handling every data point pair as a DB Entry. Now every is fine again.
best wishes

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
How about adding short comments to the mysterious variables like 
````
int correct = 0;
boolean isData = false;
int sep = -1;
````
Having the variables defined might help to avoid similar problems in the future.

**Comment by Annexhc** [comment]
Yes, I agree! It is especially important when we are working together on the same classes. And you are also right that some of these variables are indeed mysterious, because it seems they are leftovers from the previous data structure....

**Comment by tomas-pluskal** [comment]
@Annexhc @robinschmid 
Should I merge this now, or are you planning to add more comments to the code?

**Comment by robinschmid** [comment]
Hey Ansgar and Tomas,

this bug was introduced in your last PR in commit 6d4aa3c

The correct version was
else if (isData)  versus the current  if(isData)

I am currently working on an mgf parser and I can fix the msp parser. 


Cheers
Robin

**Comment by Annexhc** [comment]
alright Robin, I will close this pull request.

**Pull request closed without merging**
