### PR TITLE
Copy of the chromatogram classes which are to be modified

### PR DESCRIPTION
**Pull request by VilhoKivihalme**

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Hi Vilho,
Nice to meet you. How about providing a bit of explanation what this pull request is about?
Thanks,
Tomas

**Comment by VilhoKivihalme** [comment]
Hello,

Looks like this pull request was an accident, I'm not used to the interface
of the github as I've been using other services before. This may be
cancelled and I'll make another once I have something real to commit.

-Vilho



5.6.2017 16.49 "Tomáš Pluskal" <notifications@github.com> kirjoitti:

**Comment by tomas-pluskal** [comment]
OK. What are you actually working on?

**Comment by VilhoKivihalme** [comment]
Our team in Turku University has a task to improve the chromatograms/area
calculations to suit better for direct injection mass spectrometer data. I
don't have all the details yet, I'm just a summer trainee/"the guy who
knows java" but I can provide you some better information later this week.

-Vilho K


5.6.2017 16.56 "Tomáš Pluskal" <notifications@github.com> kirjoitti:

**Comment by tomas-pluskal** [comment]
OK, sounds good. Keep me posted.

**Pull request closed without merging**
