### PR TITLE
Bugfix for #570

### PR DESCRIPTION
**Pull request by asmirn1**
Hi Tomas,

@glerny is right in his description of this bug:
> I believe it is more a problem with the mzML files (converted from TIF to mzML with MSConvert) before or after the MassDetection step (exact mass with a threshold at 1,000) as the same parameters work with other files. I assume the NaN values result from one of those two steps and this case is not taken into account by the ADAP algorithms. I just test it using a threshold at 10,000 for the MassDetection (exact mass with a threshold at 10,000) and in this case, the ADAP algorithms work, so I definitely believe that during the centroidisation some errors occur that generate NaN values that bugged the ADAP algorithms (the chromatogram builder work through).

I have added a check for NaN values in ADAPChromatogramBuilder.

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Thanks, Alex, but where do the NaN values come from? They should not be there.

**Comment by asmirn1** [comment]
It's probably happens during mass detection. I can check it.

**Comment by tomas-pluskal** [comment]
Please take a look, thanks!

**Comment by asmirn1** [comment]
Function `calculateExactMass` in ExactMassDetector.java produces these NaN values. I'll see if I can fix it.

**Comment by asmirn1** [comment]
So the function `calculateExactMass` in ExactMassDetector.java would give NaN values when interpolating between two data points. In case of the zero slope between two data point, the resulting m/z value would be NaN. 

I have modified the code so that when a slope is zero, the interpolated m/z value is the average of two m/z values. Hopefully, this makes sense.

**Comment by tomas-pluskal** [comment]
That's perfect, thanks Alex!

**Comment by asmirn1** [comment]
Tomas,

I'm not sure why my code doesn't pass the check. Is it something with Java versions?

**Comment by tomas-pluskal** [comment]
Don't worry about that, there is some ongoing issue with the mvnsearch.com repository, so the test builds just time out.

**Pull request merged**
