### PR TITLE
changed MGF export header

### PR DESCRIPTION
**Pull request by du-lab**
Hi Tomas,

I herein make a PR for the changes we made to the MGF export header. This exporter is for exporting spectra constructed by the ADAP spectral deconvolution of GC-MS data.

The corresponding help file has been added as well.

Please review and let me know if you have any questions for me.

Xiuxia on behalf of the Du-Lab Team

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Thanks!

**Comment by tomas-pluskal** [comment]
Are you planning any more changes, or should I release MZmine 2.25 with your new modules?

**Comment by lfnothias** [comment]
Tomas, just to let you know we are preparing in coordination Xiuxia to adapt the MGF export to LC-MS/MS. We will push the changes probably tomorrow afternoon.

**Comment by du-lab** [comment]
Tomas,

The major modules of ADAP-GC are already all part of MZmine 2 and I expect that changes in the near future will be relatively minor. So you may release MZmine 2.25 now.

We are working on a parameter-free (or much fewer parameters) spectral deconvolution, but this will take a while.

**Pull request merged**
