### PR TITLE
Added MS Level to targeted peak filtering.

### PR DESCRIPTION
**Pull request by AndriusC**
Any changes or ideas on how the code can be improved will be appreciated.
(Re-push requesting as I messed around with branches and deleted the old one)

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Looks good, thanks! 

Just one concern: most of the diff are just formatting changes. We use Google Java Code Style (https://github.com/google/styleguide) to format our sources. Could you set your IDE to use that style and reformat the files that you modified in your pull requests?

**Comment by AndriusC** [comment]
I am pretty certain that I installed a plugin that does exactly that thing, formats it in Google Java Code Style (https://plugins.jetbrains.com/plugin/8527-google-java-format) is this wrong? I never found that code style in IntelliJ by default.

**Comment by tomas-pluskal** [comment]
Ah, sorry, I think you're right. The changes are probably because the previous version of the file was formatted with an old style.

**Comment by AndriusC** [comment]
Although I'm not sure now, I got the code style from the link you gave me and it changed spacing(from the left side) and changed stuff like this:
if ... 
continue;

into

if .. {
continue;
}

**Pull request merged**
