### PR TITLE
Diagnostic Fragmentation Filter

### PR DESCRIPTION
**Pull request by shawnhoogstra**
As a team we developed and coded a module for use in MZmine2 to enable the efficient screening of MS/MS datasets for class‐specific product ions(s) and/or neutral loss(es). For a detailed view on how we utilized this module and on the output we received see the paper: 

Walsh, J. P., Renaud, J. B., Hoogstra, S., McMullin, D. R., Ibrahim, A., Visagie, C., ... & Sumarah, M. W. (2018). Diagnostic Fragmentation Filtering for the Discovery of New Chaetoglobosins and Cytochalasins. _Rapid Communications in Mass Spectrometry._

Or view it at this link: https://onlinelibrary.wiley.com/doi/abs/10.1002/rcm.8306

It is based upon the neutral loss visualization module with distinct changes for filtering. We have been asked consistently for this module so we are hoping to get it into the main version of MZmine2 as currently we have to pass it on through google drive. Lastly, we are in the process of publishing a walk-through of our protocol and of the module on JoVE.

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Hi!

It looks like a very useful contribution, thank you!

A few comments from my side:
- The Travis log indicates a compilation error, please address that:
````
([ERROR] /home/travis/build/mzmine/mzmine2/src/main/java/net/sf/mzmine/modules/visualization/productionfilter/ProductIonFilterDataSet.java:[34,1] net.sf.mzmine.modules.visualization.productionfilter.ProductIonFilterDataSet is not abstract and does not override abstract method getTaskPriority() in net.sf.mzmine.taskcontrol.Task)
````
- Please format the source code files according to the Google code style (https://github.com/google/styleguide). This can be done automatically by most IDEs. 
- Please add a help file (HTML) for your module, in a similar fashion to other modules and plots. The help file should describe the function and meaning of all parameters.

**Comment by tomas-pluskal** [comment]
Also, please add the GPL license header to all new files (copy & paste from any existing file).

**Comment by shawnhoogstra** [comment]
Thanks!

Made the necessary changes. Working on solving the Travis log compilation error.

**Comment by tomas-pluskal** [comment]
Thanks!
I just noticed the license header is missing in ListDoubleParameter.java and ListDoubleComponent.java

**Comment by shawnhoogstra** [comment]
Fixed! Sorry about missing that.

**Comment by tomas-pluskal** [comment]
Awesome, thanks!
I'll merge this PR now and I'll send more comments later after doing some testing.

**Pull request merged**
