### PR TITLE
Moved cos scorce to comment

### PR DESCRIPTION
**Pull request by Annexhc**
Hi Tomas,
this pull request fixes issue #627.
Ansgar

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Thanks, Ansgar.
Now looking at the code, I have some doubt whether this is the best solution. Each peak list row can have multiple identities assigned to it, but only one comment field. If during the spectral matching two possible hits are assigned to the peak list row, the comment field will create confusion, don't you think?

**Comment by Annexhc** [comment]
Oh yeah that is really not great. What is your suggestion? We could add all identities to the comment as well. This could result in very long comments thought.

**Comment by tomas-pluskal** [comment]
I think a better solution is to make sure that two PeakIdentity instances are considered same when they refer to the same library spectrum, but disregarding the cosine similarity. That means overriding the equals() method in SpectralDBPeakIdentity, and making sure that the Join Aligner actually uses the equals() method to check whether two identities are the same.

**Comment by Annexhc** [comment]
Hey Tomas, sorry for the delay. Your solution sounds way better. I will think about the implementation.

Still I have one concern. What if the database contains more than one spectrum for the same compound, e.g. in GC-MS one deconvoluted, the other not? Or more likely, two spectra for the same compound acquired with different instruments (QTOF vs. Orbitrap)?

What do you think about adding a new parameter to the PeakIdentity, something like "Identiification method". There we could store the applied identification module and other related information like the cos score. 
image

**Comment by robinschmid** [comment]
We need a multi layered comparison of the library hits. 
The best description should be the structure as InChI or SMILES. @tomas-pluskal do you know of a structure comparison method (e.g., in the CDK)?

1. Compare structure (with or without stereochemistry)
2. Compare mol. formula???
3. Compare name (ignoreCase; which can be very different and unprecise depending on the library entry)

**Comment by tomas-pluskal** [comment]
The spectral matching module is supposed to match spectra, not compounds. So I think if the database contains multiple spectra of the same compound, these should be still reported as separate hits.

Perhaps the best solution would be to extend the data model, so for each PeakListRow, we can record
- chemical structure, if known (this can be shown in the peak list table)
- chemical formula (of the neutral molecule)
- ionization type/adduct
- database hits/prediction results with scores - here we can aggregate the results of the different search methods. The user can then pick their favorite result (compound) and transfer it to the "chemical structure" field

@Annexhc We have the property "Identification method" in Peak Identity (https://github.com/mzmine/mzmine2/blob/master/src/main/java/net/sf/mzmine/datamodel/PeakIdentity.java#L36), but the dialog could certainly be improved

**Comment by Annexhc** [comment]
Okay Tomas, I understand your point. The extension of the data model would be great. I think @robinschmid has done a lot of that already in his ion identity branch.

**Comment by robinschmid** [comment]
They should definitely be reported separately. A way of comparing spectral library matches or structures in general would still be very helpful (e.g., to find the best common structure, to compare IDs in join aligner (see issue #627), ...)

I already changed the structure in one of my development branches for ion identity networking:
- group ID (grouped features)
  - ion identity network ID (ions of the same neutral molecule)
  - Ion identity (adduct)
    - neutral mass
    - molecular formula
  - best average formula for all ions (for an ion identity network)

**Comment by Annexhc** [comment]
I think, I will close this PR for now. I will work again on issue #627 in the future when Robin has implemented his changes to the data model. As pointed out in this discussion, the changes I did so far have to many drawbacks.

**Pull request closed without merging**
