### PR TITLE
KMD RKM and charge row filter

### PR DESCRIPTION
**Pull request by Annexhc**
Hi Tomas,
I have added new filter options for the peak list row filter. Kendrick mass defect filter, remainder of Kendrick mass filter, and charge filter. 
I was surprised we didnt have the last one already. Please correct me if we already had it.
best wishes,
Ansgar 
image

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Thanks @Annexhc 
Perhaps you could also add the above screenshot to the help file of the module and explain the purpose of this particular filter there?

**Comment by Annexhc** [comment]
good idea!

**Comment by Annexhc** [comment]
all done!

**Comment by tomas-pluskal** [comment]
Thanks!

**Pull request merged**
