### PR TITLE
Update Blank subtraction

### PR DESCRIPTION
**Pull request by SteffenHeu**
Hi Tomas,

if it's not too late i'd like to submit this PR. The changes implement the suggestions you made #742. The module is now working on an aligned feature list and selecting raw data files. 
Otherwise i can merge this manually after the change.

Best
Steffen

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Ok, I'll take care of this!

**Comment by tomas-pluskal** [comment]
It seems some classes are missing:
````
import net.sf.mzmine.modules.peaklistmethods.filtering.blanksubtraction.PeakListBlankSubtractionMasterTask.MatchingParameter;
import net.sf.mzmine.modules.peaklistmethods.filtering.blanksubtraction.PeakListBlankSubtractionMasterTask.SubtractionType;
````

**Comment by tomas-pluskal** [comment]
I would prefer if you don't use inner classes for things like parameters or enums. Shorter class files are always easier to read and navigate, so it is better if you move these to a separate .java file.

**Comment by SteffenHeu** [comment]
Ok!
Oops. I deleted those definitions when I removed old code but I guess I forgot to update the imports. They are not needed anymore. Do you want me to make a pr with them removed or do you just update the imports?

**Comment by tomas-pluskal** [comment]
But the classes are still used inside the PeakListBlankSubtractionSingleTask class, so I cannot just remove the imports

**Comment by Sukis123** [comment]
@SteffenHeu @tomas-pluskal Hi, is the blank subtraction function available now? by the way, how can I know if there are new functions available in MZmine 2? Will all new features be included in the latest version?

**Comment by SteffenHeu** [comment]
It is not included in the latest release, as it is not fully finished. 
If you wish to build your own mzmine version with the module, you just have to enable it here:

https://github.com/mzmine/mzmine2/blob/5739e1b01dac009c91b1b1f574d65f14832d3b7c/src/main/java/net/sf/mzmine/main/MZmineModulesList.java#L313

Please bear in mind that the module is not finished and has not been tested thoroughly and might lead to unexpected results.

**Comment by Annexhc** [comment]
You can always check out new functionalities in the change log:
https://mzmine.github.io/changelog.html

**Comment by Sukis123** [comment]
@SteffenHeu Thank you very much. I will take a look.

**Comment by Sukis123** [comment]
@Annexhc Get it. Thanks a lot.

**Comment by ogomaa** [comment]
Hi,
I am trying to follow this thread on how to subtract blank features but I couldn't get the answer. is there a documentation for this function/workflow?
Thanks,
Osama

**Pull request merged**
