### PR TITLE
Option to remove empty rows after PeakFilter

### PR DESCRIPTION
**Pull request by robinschmid**
Hey Tomas,

this is a small addition to the PeakFilter module. If the resulting feature list row is empty - it can now be removed automatically. Previously, we had to run PeakFilter + FeatureListRowFIlter (min features=1) to do this.

Cheers
Robin

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Hmm, maybe removing empty rows should just be enforced in all cases? Seems like it serves no purpose to keep empty rows.

**Comment by robinschmid** [comment]
Yeah this was my first plan but then I decided for the "compatibility" version.

Gonna change it to always - its a better user experience.

**Comment by robinschmid** [comment]
Done.

**Comment by tomas-pluskal** [comment]
Thanks Robin!

**Pull request merged**
