### PR TITLE
Rserve integration 3.1

### PR DESCRIPTION
**Pull request by golgauth**
Migration of the baseline correction module to use Rserve.
Removed the conflicting file "HeatMapTask.java" we had both changed...

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Looks good, I'll merge it. 
For future commits, coudl you please set your editor/IDE to indent using spaces instead of tabs?

**Comment by golgauth** [comment]
Well, since I know exactly what files I modified, this would be easier to fix this at the and of my pull requests stack. Otherwise, I'll have more conflicts to deal with, I suppose (each branch expands from the previous one).

I gonna see if I get into trouble doing this now, or not.

**Comment by golgauth** [comment]
By the way, I noticed you systematically quite unindent the code and wrap/limit the width of the text (what is the number of characters required?). It seems you're using eclipse as well: so may be you could give me the whole settings required for formatting before commit.

Thanks.

**Comment by tomas-pluskal** [comment]
Please find attached the formatting style for Eclipse.

If you're using Eclipse, please format the sources before committing, and
also organize the imports (it's Command+Shift+O on Mac, not sure about
other platforms). It would be also nice if you cleanup the unused
(commented-out) code unless you are planning to use it in the future.

Tomas

**Comment by golgauth** [comment]
Thanks, I'll apply those settings to eclipse (I already did some changes for tabs to spaces, ...).
Regarding the commented lines, I usually cleanup as much as I can, except for things that I assume not completely done (or could be better). So, in theory, this will be completely clean a bit later ;)

**Comment by golgauth** [comment]
Note about this pull request (3.1): The code shouldn't compile due to HeatMapTask.java being outdated (struggling with Git, sorry). You'll find the right one in next pull request (4.1) or in my "rserve-integration-4.1" branch.

**Pull request merged**
