### PR TITLE
Fixed matrix vs vector 'collect' handling.

### PR DESCRIPTION
**Pull request by golgauth**
For real this time. Previous way was confusing...

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
The commit history looks a bit wild.. :)

**Comment by golgauth** [comment]
Yep I know, still learning proper usage of git. But I'm getting better... trust me ;)

**Comment by tomas-pluskal** [comment]
Check here, for example: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by golgauth** [comment]
Ok, I see. Pretty handy. I'll do that next time.
Cheers.

**Pull request merged**
