### PR TITLE
Update: ADAP mgf export

### PR DESCRIPTION
**Pull request by robinschmid**
Hey @tomas-pluskal ,
Hey @asmirn1 (@du-lab),

for a current project, I needed to change a few things in the MGF export.

- Changed the name to **Export to MGF file (ADAP clusters)**
- package name and module name
- added number formatting to the export (uses MZmine preferences - or nominal mass)
- Main changes are in the **AdapMgfExportTask**:
    - Selection of the representative m/z
    - use average m/z rather than a single features m/z

@asmirn1 is this ok to you and your lab?

Cheers
Robin

### CODE REVIEW

**Comment by asmirn1** [comment]
Hi @robinschmid 

I'm not sure what **(ADAP clusters)** means. Maybe, **Export to MGF file (ADAP)** will be better?

**Comment by robinschmid** [comment]
I can change that.

How do you usually refer to the clustering results of the ADAP modules?
Pseudo spectra? clustered spectra?

**Comment by asmirn1** [comment]
We usually use the terms "pure fragmentation spectra" for GC-MS data, and "pseudo-spectra" for LC-MS data.

**Comment by asmirn1** [comment]
I'll ask Xiuxia (@du-lab) if she is okay with this and all other changes.

**Comment by robinschmid** [comment]
Thank you. 
I have changed the name to the one you have proposed

**Comment by asmirn1** [comment]
@robinschmid 
That's great that you started cleaning up MZmine! Let me know when you find any other issues with our code.

**Comment by tomas-pluskal** [comment]
There is a conflict now after I merged the other PR.

**Comment by tomas-pluskal** [comment]
@robinschmid I suggest we work on redesigning the MZmine data model while you are in Boston. It is an important task so it will be good to think it through carefully together.

**Comment by robinschmid** [comment]
Ok I have also reflected this to the MSPExport.
- both are in the package io.adap. xxx
- Names are similar
- class names are similar

Can be merged from my side.

**Comment by tomas-pluskal** [comment]
Thanks Robin!

**Pull request merged**
