### PR TITLE
Changed allMS2Scans to empty array

### PR DESCRIPTION
**Pull request by robinschmid**
Based on PR #532 

I have changed all files to an empty array. The project save and load function should still work. Your lipid module as well. 

@Annexhc please test it. 

Cheers
Robin

### CODE REVIEW

**Comment by Annexhc** [comment]
looks good to me! I will test it after tomas has merged it, cheers!

**Comment by robinschmid** [comment]
You can also directly fetch my branch
robinschmid:tomasmaster_new_msms_struc

**Comment by Annexhc** [comment]
good idea, I will test it

**Comment by Annexhc** [comment]
okay, I did some testing. Your changes work fine but I have noticed an other bug, which was my bad. After saving and reopening all MS2 fragment scans are removed except the last one. I know were I have to change the code. What is the easiest way to do it? merging this branch as it is and I will make a new pull request?

**Comment by tomas-pluskal** [comment]
Sounds good to me.

**Pull request merged**
