### PR TITLE
Bugfix for #615

### PR DESCRIPTION
**Pull request by asmirn1**
Fix a bug in ADAP when the upper and lower wavelet scales are the same.
Update the ADAP version.

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Thanks, Alex. 

Don't you think it might be a good idea to update the parameter class in MZmine to prevent the user from setting the same upper and lower scales?

**Comment by asmirn1** [comment]
Sure. I guess the best way to do it would be using `UserParameter.checkValue()`? Let me figure out how you are using this method.

**Comment by asmirn1** [comment]
I've created a new class DoubleNonEmptyRangeParameter that extends DoubleRangeParameter. Will this work?

**Comment by tomas-pluskal** [comment]
It seems like an overkill to create a new class that duplicates the existing functionality. Why not add a simple property to the existing DoubleRangeParameter?

**Comment by asmirn1** [comment]
I've updated DoubleRangeParameter and removed DoubleNonEmptyRangeParameter

**Comment by tomas-pluskal** [comment]
Looks good, thanks!

**Pull request merged**
