### PR TITLE
Spectral library creation/submission - restructure

### PR DESCRIPTION
**Pull request by robinschmid**
Hey Tomas,

this PR relates to issue #583.

I am still working on it - this PR is just so that you can see the progress. I will tell you when everything is done. 

Implemented so far:
 - Separate parameters for scan selection and processing, GNPS submission, and metadata
 - Module to keep the main parameters (not metadata param)
 - m/z formatting for export
 - Help button and file

Cheers
Robin

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Hi Robin, there is a conflict in MZmineModulesList.java with the recent additions from Ansgar.

**Comment by tomas-pluskal** [comment]
So, what is the reason you decided not to use the ParameterSetupDialog for the MSMSLibrarySubmissionWindow?

**Comment by robinschmid** [comment]
> Hi Robin, there is a conflict in MZmineModulesList.java with the recent additions from Ansgar.

Resolved

**Comment by robinschmid** [comment]
> So, what is the reason you decided not to use the ParameterSetupDialog for the MSMSLibrarySubmissionWindow?

First, I would like to have it as a window not a dialog (window decorators, maximize, ...)
Moreover, this window does way more than just setting up parameters - and it sets up multiple sets of parameters.

We can change it to a ParameterSetupDialog later if this is useful.

**Comment by robinschmid** [comment]
From my side, it is all setup to be merged.

The latest changes include:
 - A results text pane at the bottom
 - All parameters were changed and grouped
 - the SpectraVisualizer has a new export to library button
 - Generation of MS1 library entires
    - e.g., GC-EI-MS or other methods with higher in-source fragmentation
    - without precursor mz, adduct, charge
    - from peaklist rows or scans in the SpectraVisualizer

**Comment by tomas-pluskal** [comment]
It looks good to me. I didn't go through every line of code, but I'll merge it, do some testing, and provide feedback if something doesn't work as expected.

**Comment by robinschmid** [comment]
Great

**Pull request merged**
