### PR TITLE
m/z distribution histogram

### PR DESCRIPTION
**Pull request by robinschmid**
Hey tomas,

this module plots an m/z histogram of m/z values in mass lists across scans. I mainly used it for direct infusion and imaging data, as we can expect more scans to contain the same m/z values. However, it is also applicable to chromatography data. 

Together with the integrated Gaussian fit function, it might be useful to analyse the distribution widths of m/z values. 

Cheers,
Robin

You can download a video of the functions from our university servers: 
[https://uni-muenster.sciebo.de/s/65FPR5Mkf496ZLQ/download](url)
 

dialog
image
image
image

### CODE REVIEW

**Comment by robinschmid** [comment]
Do I have to do anything about this failing?
I took your master branch and merged all my changes.

image

**Comment by tomas-pluskal** [comment]
Don't worry about the failing build, it is not caused by you.

**Comment by robinschmid** [comment]
Alright. 
I hope you and the other users will like the changes. 

Cheers,
Robin

**Comment by tomas-pluskal** [comment]
Hi Robin,
The module looks good to me! Regarding the video - why don't you upload it to Youtube and add a link to it to the Help page?

**Pull request merged**
