### PR TITLE
Changed to new GNPS submission address, added password and username

### PR DESCRIPTION
**Pull request by robinschmid**
Hey Tomas, Hey Ming,

I have added the password and username option to the direct GNPS submission and moved the address to

http://dorresteinappshub.ucsd.edu:5050/uploadanalyzefeaturenetworking

@mwang87 , is this the final address? Or are you planning to change the address again?

The password is not encrypted and just send as a String. What is the best way to handle this?

Cheers
Robin

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
I'd say sending a plain-text password over HTTP is not ideal. Does the server support HTTPS?

**Comment by robinschmid** [comment]
I have talked to ming. Their plan is to move the server to a final location with https. 
However, this might take a while. 
As this parameter is optional for GNPS we could just mention it in the help file  the description and maybe in the parameter name - what fo you think?

**Comment by tomas-pluskal** [comment]
Sounds good!

Tomas

**Comment by robinschmid** [comment]
I have changed the parameter name, added some comments in the help file and this should be enough to notify everyone that the password is sent without encryption.
This should be fine to merge.

**Comment by tomas-pluskal** [comment]
Awesome, thanks!

**Pull request merged**
