### PR TITLE
Spectral match results changes

### PR DESCRIPTION
**Pull request by robinschmid**
This is a first fix for the spectral match results visualisation:
- Color scale from red - to green (score = 0.5 to 1.0, respectively)
- Sizes of meta data panel and chart

A problem with the layout remains. Somehow, the meta data is visualised with larger height (also the structure). Suddenly after scrolling down, everthing changed to the actual layout. I did revalidate on every change but still...

image
image

### CODE REVIEW

**Comment by robinschmid** [comment]
Ok fixed it. And the structure is a bit easier
image

**Comment by Annexhc** [comment]
wow, that is some short code :-D very nice. Can you change the background of "Compound information", "Instrument information" etc. back to white? I think that would look more fancy. The gray boxes have a little gap.

**Comment by robinschmid** [comment]
I actually like the gray background. It is like a header

**Comment by Annexhc** [comment]
But we already have the bold text as a header. What I really don't like is the gap in between the boxes.
gap

**Comment by robinschmid** [comment]
This should cover everything. 
- the MoNA json parsing is faster by keeping the reading and parsing in separate threads
- the width of the meta data panel is fixed
- there is a JCheckBoxMenuItem to toggle the zoom coupling of the two intensity axes
- title bar has auto wrapping and size now

image

**Comment by robinschmid** [comment]
From my side, everything is ready to be merged.

**Comment by tomas-pluskal** [comment]
Looks good, thanks!

**Pull request merged**
