### PR TITLE
Bugfix/alignment/missing spectra

### PR DESCRIPTION
**Pull request by asmirn1**
I've found a bug: the features produced by ADAPAligner would not contain any fragmentation spectra (isotopic distributions). 

This PR fixes that.

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Thanks, Alex!

**Comment by asmirn1** [comment]
@tomas-pluskal 

Btw, when I execute `mvn install` or `mvn clean install`, it takes forever (about 30 minutes) to download MZmine dependencies. It seems that the repository at [http://www.mvnsearch.org/maven2](http://www.mvnsearch.org/maven2) is very slow. Do you know any solution for this?

I know that I can use Eclipse or IntelliJ IDEA to quickly build the project. But I still use `mvn install` to produce file `target/MZmine-2.XX.zip`.

**Comment by tomas-pluskal** [comment]
I know about this problem, but in any case I am planning to switch the
build tool from maven to gradle, which works much better.

The gradle build file is already there, you can try running "gradle
runtime". The build requires Java 12 and the java runtime will be included
in MZmine installation, so the users don't need to install java separately
anymore.

I am just waiting for the new JavaFX 3D visualizer to be merged, because
that is the last piece of code that is preventing us from moving to newer
versions of Java. It will be done in a few weeks.

Best,

Tomas

**Comment by asmirn1** [comment]
Great, thank you!

**Comment by asmirn1** [comment]
Tomas,

I've installed JDK 12 but gradle didn't work for me either. I'm attaching the output of `gradle runtime` if you are interested. Any suggestions why it doesn't work?

[output.txt](https://github.com/mzmine/mzmine2/files/3439413/output.txt)

Sorry for questions - I haven't used Gradle before.

**Comment by tomas-pluskal** [comment]
Hi Alex,

I think it is working, it's just that the EBI Maven repo is down, and
that's why your build failed. I don't know why the repo is down, it was
working yesterday. I suppose they will fix it soon.

Best,

Tomas

**Comment by asmirn1** [comment]
Okay. Thank you!

**Comment by tomas-pluskal** [comment]
It seems the EBI repo is back up again.

**Comment by asmirn1** [comment]
Alright. I'll try Gradle again.

**Pull request merged**
